export interface ICliente {
  id: number;
  nombre: string;
  apellidos: string;
  usuario: string;
  pais: string;
  fechaNacimiento: Date;
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< main
    trabajo?: string;  // Asegúrate de incluir todas las propiedades necesarias
    correo?: string;   // Agrega la propiedad correo aquí
  }
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
}
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> info_cliente_recibe
