// <auto-generated />
using System;
using ApiClases_20270722_Proyecto.ContextoCarpeta;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiClases_20270722_Proyecto.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240731073901_masdatos2")]
    partial class masdatos2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiClases_20270722_Proyecto.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Juanes",
                            FechaNacimiento = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ana",
                            Pais = "Reino Unido",
                            Usuario = "ana777"
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Sanchez",
                            FechaNacimiento = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Pedro",
                            Pais = "Estados Unidos",
                            Usuario = "elcoletas"
                        },
                        new
                        {
                            Id = 3,
                            Apellidos = "Martinez",
                            FechaNacimiento = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Miguel",
                            Pais = "España",
                            Usuario = "emanems"
                        },
                        new
                        {
                            Id = 4,
                            Apellidos = "Lopez",
                            FechaNacimiento = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Juan",
                            Pais = "España",
                            Usuario = "jujalag"
                        },
                        new
                        {
                            Id = 5,
                            Apellidos = "Vertiz",
                            FechaNacimiento = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Iñigo",
                            Pais = "Andorra",
                            Usuario = "ibai"
                        },
                        new
                        {
                            Id = 6,
                            Apellidos = "Obama",
                            FechaNacimiento = new DateTime(1961, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Barack",
                            Pais = "Estados Unidos",
                            Usuario = "baracko"
                        },
                        new
                        {
                            Id = 7,
                            Apellidos = "Messi",
                            FechaNacimiento = new DateTime(1987, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Lionel",
                            Pais = "Argentina",
                            Usuario = "leomessi"
                        },
                        new
                        {
                            Id = 8,
                            Apellidos = "Musk",
                            FechaNacimiento = new DateTime(1971, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Elon",
                            Pais = "Sudáfrica",
                            Usuario = "elonmusk"
                        },
                        new
                        {
                            Id = 9,
                            Apellidos = "Winfrey",
                            FechaNacimiento = new DateTime(1954, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Oprah",
                            Pais = "Estados Unidos",
                            Usuario = "oprahw"
                        },
                        new
                        {
                            Id = 10,
                            Apellidos = "Gates",
                            FechaNacimiento = new DateTime(1955, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Bill",
                            Pais = "Estados Unidos",
                            Usuario = "billgates"
                        },
                        new
                        {
                            Id = 11,
                            Apellidos = "Merkel",
                            FechaNacimiento = new DateTime(1954, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Angela",
                            Pais = "Alemania",
                            Usuario = "angelam"
                        },
                        new
                        {
                            Id = 12,
                            Apellidos = "Ripoll",
                            FechaNacimiento = new DateTime(1977, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Shakira",
                            Pais = "Colombia",
                            Usuario = "shakira"
                        },
                        new
                        {
                            Id = 13,
                            Apellidos = "Jobs",
                            FechaNacimiento = new DateTime(1955, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Steve",
                            Pais = "Estados Unidos",
                            Usuario = "stevejobs"
                        },
                        new
                        {
                            Id = 14,
                            Apellidos = "Zuckerberg",
                            FechaNacimiento = new DateTime(1984, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Mark",
                            Pais = "Estados Unidos",
                            Usuario = "markz"
                        },
                        new
                        {
                            Id = 15,
                            Apellidos = "Williams",
                            FechaNacimiento = new DateTime(1981, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Serena",
                            Pais = "Estados Unidos",
                            Usuario = "serenaw"
                        },
                        new
                        {
                            Id = 16,
                            Apellidos = "Ronaldo",
                            FechaNacimiento = new DateTime(1985, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Cristiano",
                            Pais = "Portugal",
                            Usuario = "cr7"
                        },
                        new
                        {
                            Id = 17,
                            Apellidos = "James",
                            FechaNacimiento = new DateTime(1984, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "LeBron",
                            Pais = "Estados Unidos",
                            Usuario = "lebronj"
                        },
                        new
                        {
                            Id = 18,
                            Apellidos = "Kagan",
                            FechaNacimiento = new DateTime(1960, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Elena",
                            Pais = "Estados Unidos",
                            Usuario = "elenak"
                        },
                        new
                        {
                            Id = 19,
                            Apellidos = "Rowling",
                            FechaNacimiento = new DateTime(1965, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "J.K.",
                            Pais = "Reino Unido",
                            Usuario = "jkrowling"
                        },
                        new
                        {
                            Id = 20,
                            Apellidos = "Johnson",
                            FechaNacimiento = new DateTime(1972, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Dwayne",
                            Pais = "Estados Unidos",
                            Usuario = "therock"
                        });
                });

            modelBuilder.Entity("ApiClases_20270722_Proyecto.Entidades.Transaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CantidadEnvia")
                        .HasColumnType("float");

                    b.Property<double>("CantidadRecibe")
                        .HasColumnType("float");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEnvia")
                        .HasColumnType("int");

                    b.Property<int>("IdRecibe")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transacciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CantidadEnvia = 1000.5,
                            CantidadRecibe = 1130.5699999999999,
                            Fecha = new DateTime(2015, 3, 15, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 6,
                            IdRecibe = 7
                        },
                        new
                        {
                            Id = 2,
                            CantidadEnvia = 2000.75,
                            CantidadRecibe = 2560.96,
                            Fecha = new DateTime(2018, 6, 10, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 8,
                            IdRecibe = 9
                        },
                        new
                        {
                            Id = 3,
                            CantidadEnvia = 1500.25,
                            CantidadRecibe = 1740.29,
                            Fecha = new DateTime(2020, 8, 21, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 10,
                            IdRecibe = 11
                        },
                        new
                        {
                            Id = 4,
                            CantidadEnvia = 2500.3299999999999,
                            CantidadRecibe = 3500.46,
                            Fecha = new DateTime(2011, 11, 30, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 12,
                            IdRecibe = 13
                        },
                        new
                        {
                            Id = 5,
                            CantidadEnvia = 3000.6700000000001,
                            CantidadRecibe = 4260.9499999999998,
                            Fecha = new DateTime(2017, 2, 7, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 14,
                            IdRecibe = 15
                        },
                        new
                        {
                            Id = 6,
                            CantidadEnvia = 4000.9899999999998,
                            CantidadRecibe = 2920.73,
                            Fecha = new DateTime(2021, 12, 25, 19, 45, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 16,
                            IdRecibe = 17
                        },
                        new
                        {
                            Id = 7,
                            CantidadEnvia = 500.44999999999999,
                            CantidadRecibe = 790.58000000000004,
                            Fecha = new DateTime(2012, 4, 18, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 18,
                            IdRecibe = 19
                        },
                        new
                        {
                            Id = 8,
                            CantidadEnvia = 600.35000000000002,
                            CantidadRecibe = 888.48000000000002,
                            Fecha = new DateTime(2019, 7, 13, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 20,
                            IdRecibe = 6
                        },
                        new
                        {
                            Id = 9,
                            CantidadEnvia = 700.12,
                            CantidadRecibe = 1085.55,
                            Fecha = new DateTime(2014, 5, 9, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 7,
                            IdRecibe = 8
                        },
                        new
                        {
                            Id = 10,
                            CantidadEnvia = 800.75,
                            CantidadRecibe = 1240.9200000000001,
                            Fecha = new DateTime(2016, 9, 14, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 9,
                            IdRecibe = 10
                        },
                        new
                        {
                            Id = 11,
                            CantidadEnvia = 900.63,
                            CantidadRecibe = 1350.3599999999999,
                            Fecha = new DateTime(2022, 3, 12, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 11,
                            IdRecibe = 12
                        },
                        new
                        {
                            Id = 12,
                            CantidadEnvia = 100.90000000000001,
                            CantidadRecibe = 140.72999999999999,
                            Fecha = new DateTime(2023, 1, 1, 6, 45, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 13,
                            IdRecibe = 14
                        },
                        new
                        {
                            Id = 13,
                            CantidadEnvia = 200.33000000000001,
                            CantidadRecibe = 246.40000000000001,
                            Fecha = new DateTime(2024, 6, 17, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 15,
                            IdRecibe = 16
                        },
                        new
                        {
                            Id = 14,
                            CantidadEnvia = 300.5,
                            CantidadRecibe = 402.67000000000002,
                            Fecha = new DateTime(2013, 2, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 17,
                            IdRecibe = 18
                        },
                        new
                        {
                            Id = 15,
                            CantidadEnvia = 400.80000000000001,
                            CantidadRecibe = 548.34000000000003,
                            Fecha = new DateTime(2020, 8, 11, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 19,
                            IdRecibe = 20
                        },
                        new
                        {
                            Id = 16,
                            CantidadEnvia = 5000.9499999999998,
                            CantidadRecibe = 7250.4399999999996,
                            Fecha = new DateTime(2010, 12, 31, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 6,
                            IdRecibe = 7
                        },
                        new
                        {
                            Id = 17,
                            CantidadEnvia = 3500.4499999999998,
                            CantidadRecibe = 4270.8699999999999,
                            Fecha = new DateTime(2017, 11, 5, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 8,
                            IdRecibe = 9
                        },
                        new
                        {
                            Id = 18,
                            CantidadEnvia = 6000.25,
                            CantidadRecibe = 7680.3500000000004,
                            Fecha = new DateTime(2015, 3, 24, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 10,
                            IdRecibe = 11
                        },
                        new
                        {
                            Id = 19,
                            CantidadEnvia = 4200.6700000000001,
                            CantidadRecibe = 4980.1199999999999,
                            Fecha = new DateTime(2019, 5, 22, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 12,
                            IdRecibe = 13
                        },
                        new
                        {
                            Id = 20,
                            CantidadEnvia = 4800.8500000000004,
                            CantidadRecibe = 6960.3999999999996,
                            Fecha = new DateTime(2011, 10, 10, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 14,
                            IdRecibe = 15
                        },
                        new
                        {
                            Id = 21,
                            CantidadEnvia = 5500.25,
                            CantidadRecibe = 8030.5,
                            Fecha = new DateTime(2021, 7, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 16,
                            IdRecibe = 17
                        },
                        new
                        {
                            Id = 22,
                            CantidadEnvia = 3100.3400000000001,
                            CantidadRecibe = 4327.1499999999996,
                            Fecha = new DateTime(2018, 4, 2, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 18,
                            IdRecibe = 19
                        },
                        new
                        {
                            Id = 23,
                            CantidadEnvia = 2900.75,
                            CantidadRecibe = 3357.8600000000001,
                            Fecha = new DateTime(2014, 11, 19, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 20,
                            IdRecibe = 6
                        },
                        new
                        {
                            Id = 24,
                            CantidadEnvia = 1700.4400000000001,
                            CantidadRecibe = 2400.6300000000001,
                            Fecha = new DateTime(2023, 8, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 7,
                            IdRecibe = 8
                        },
                        new
                        {
                            Id = 25,
                            CantidadEnvia = 650.91999999999996,
                            CantidadRecibe = 995.71000000000004,
                            Fecha = new DateTime(2012, 6, 5, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 9,
                            IdRecibe = 10
                        },
                        new
                        {
                            Id = 26,
                            CantidadEnvia = 4500.5500000000002,
                            CantidadRecibe = 6120.8800000000001,
                            Fecha = new DateTime(2020, 1, 27, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 11,
                            IdRecibe = 12
                        },
                        new
                        {
                            Id = 27,
                            CantidadEnvia = 3800.6799999999998,
                            CantidadRecibe = 4346.7799999999997,
                            Fecha = new DateTime(2022, 4, 8, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 13,
                            IdRecibe = 14
                        },
                        new
                        {
                            Id = 28,
                            CantidadEnvia = 2700.4499999999998,
                            CantidadRecibe = 3159.52,
                            Fecha = new DateTime(2013, 9, 15, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 15,
                            IdRecibe = 16
                        },
                        new
                        {
                            Id = 29,
                            CantidadEnvia = 1900.3399999999999,
                            CantidadRecibe = 2652.8699999999999,
                            Fecha = new DateTime(2016, 12, 22, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 17,
                            IdRecibe = 18
                        },
                        new
                        {
                            Id = 30,
                            CantidadEnvia = 5100.1499999999996,
                            CantidadRecibe = 6120.5699999999997,
                            Fecha = new DateTime(2024, 10, 18, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 19,
                            IdRecibe = 20
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
