// <auto-generated />
using System;
using ApiClases_20270722_Proyecto.ContextoCarpeta;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiClases_20270722_Proyecto.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240730113805_transacciones añadidas")]
    partial class transaccionesañadidas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiClases_20270722_Proyecto.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Juanes",
                            FechaNacimiento = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ana",
                            Pais = "Reino Unido",
                            Usuario = "ana777"
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Sanchez",
                            FechaNacimiento = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Pedro",
                            Pais = "Estados Unidos",
                            Usuario = "elcoletas"
                        },
                        new
                        {
                            Id = 3,
                            Apellidos = "Martinez",
                            FechaNacimiento = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Miguel",
                            Pais = "España",
                            Usuario = "emanems"
                        },
                        new
                        {
                            Id = 4,
                            Apellidos = "Lopez",
                            FechaNacimiento = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Juan",
                            Pais = "España",
                            Usuario = "jujalag"
                        },
                        new
                        {
                            Id = 5,
                            Apellidos = "Vertiz",
                            FechaNacimiento = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Iñigo",
                            Pais = "Andorra",
                            Usuario = "ibai"
                        });
                });

            modelBuilder.Entity("ApiClases_20270722_Proyecto.Entidades.Transaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CantidadEnvia")
                        .HasColumnType("float");

                    b.Property<double>("CantidadRecibe")
                        .HasColumnType("float");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEnvia")
                        .HasColumnType("int");

                    b.Property<int>("IdRecibe")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transacciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CantidadEnvia = 50.5,
                            CantidadRecibe = 30.199999999999999,
                            Fecha = new DateTime(2022, 3, 15, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 1,
                            IdRecibe = 2
                        },
                        new
                        {
                            Id = 2,
                            CantidadEnvia = 70.299999999999997,
                            CantidadRecibe = 45.799999999999997,
                            Fecha = new DateTime(2023, 8, 20, 15, 10, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 2,
                            IdRecibe = 3
                        },
                        new
                        {
                            Id = 3,
                            CantidadEnvia = 25.100000000000001,
                            CantidadRecibe = 15.699999999999999,
                            Fecha = new DateTime(2024, 5, 5, 16, 20, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 3,
                            IdRecibe = 4
                        },
                        new
                        {
                            Id = 4,
                            CantidadEnvia = 40.899999999999999,
                            CantidadRecibe = 20.300000000000001,
                            Fecha = new DateTime(2025, 11, 10, 17, 45, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 4,
                            IdRecibe = 5
                        },
                        new
                        {
                            Id = 5,
                            CantidadEnvia = 60.200000000000003,
                            CantidadRecibe = 35.600000000000001,
                            Fecha = new DateTime(2026, 4, 25, 18, 55, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 5,
                            IdRecibe = 1
                        },
                        new
                        {
                            Id = 6,
                            CantidadEnvia = 72.099999999999994,
                            CantidadRecibe = 18.699999999999999,
                            Fecha = new DateTime(2027, 9, 5, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 3,
                            IdRecibe = 2
                        },
                        new
                        {
                            Id = 7,
                            CantidadEnvia = 64.799999999999997,
                            CantidadRecibe = 42.299999999999997,
                            Fecha = new DateTime(2028, 2, 15, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 4,
                            IdRecibe = 1
                        },
                        new
                        {
                            Id = 8,
                            CantidadEnvia = 91.5,
                            CantidadRecibe = 10.199999999999999,
                            Fecha = new DateTime(2029, 7, 30, 21, 5, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 5,
                            IdRecibe = 4
                        },
                        new
                        {
                            Id = 9,
                            CantidadEnvia = 38.600000000000001,
                            CantidadRecibe = 12.4,
                            Fecha = new DateTime(2030, 1, 10, 22, 20, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 2,
                            IdRecibe = 5
                        },
                        new
                        {
                            Id = 10,
                            CantidadEnvia = 55.299999999999997,
                            CantidadRecibe = 28.899999999999999,
                            Fecha = new DateTime(2031, 6, 20, 23, 40, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 1,
                            IdRecibe = 3
                        },
                        new
                        {
                            Id = 11,
                            CantidadEnvia = 80.700000000000003,
                            CantidadRecibe = 15.199999999999999,
                            Fecha = new DateTime(2032, 12, 5, 0, 10, 0, 0, DateTimeKind.Unspecified),
                            IdEnvia = 4,
                            IdRecibe = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
