// <auto-generated />
using System;
using ApiClases_20270722_Proyecto.ContextoCarpeta;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiClases_20270722_Proyecto.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240729120332_prueba2")]
    partial class prueba2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiClases_20270722_Proyecto.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Juanes",
                            FechaNacimiento = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ana",
                            Pais = "Reino Unido",
                            Usuario = "ana777"
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Sanchez",
                            FechaNacimiento = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Pedro",
                            Pais = "Estados Unidos",
                            Usuario = "elcoletas"
                        },
                        new
                        {
                            Id = 3,
                            Apellidos = "Martinez",
                            FechaNacimiento = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Miguel",
                            Pais = "España",
                            Usuario = "emanems"
                        },
                        new
                        {
                            Id = 4,
                            Apellidos = "Lopez",
                            FechaNacimiento = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Juan",
                            Pais = "España",
                            Usuario = "jujalag"
                        },
                        new
                        {
                            Id = 5,
                            Apellidos = "Vertiz",
                            FechaNacimiento = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Iñigo",
                            Pais = "Andorra",
                            Usuario = "ibai"
                        });
                });

            modelBuilder.Entity("ApiClases_20270722_Proyecto.Entidades.Transaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CantidadEnvia")
                        .HasColumnType("float");

                    b.Property<double>("CantidadRecibe")
                        .HasColumnType("float");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEnvia")
                        .HasColumnType("int");

                    b.Property<int>("IdRecibe")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transacciones");
                });
#pragma warning restore 612, 618
        }
    }
}
